import = ["~/.config/alacritty/themes/tokyo-night.toml"]
live_config_reload = true

[window]
decorations = "None"
opacity = 1.0
# position = { x = 0, y = 0 }
# padding = { x = 12, y = 12 }

[colors.primary]
background = "#000000"

[colors.cursor]
cursor = "#FFFFFF"
text = "#1E1E2E"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[font]
normal = { family = "JetBrainsMono NF" }
bold = { family = "JetBrainsMono NF" }
