#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
export FONT="SF Pro"
export NERD_FONT="SFMono Nerd Font"

source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# sketchybar --bar position=top \
# 	height=40 \
# 	blur_radius=30 \
# 	color=0x40000000

sketchybar --bar height=32 \
    blur_radius=100 \
    position=top \
    padding_left=10 \
    padding_right=10 \
    color=0x000000ff \
    shadow=on

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
    updates=when_shown
    drawing=on
    icon.font="$NERD_FONT:Regular:14.0"
    icon.color=0xffffffff
    label.font="$FONT:Light:14.0"
    label.color=0xffffffff
    label.padding_left=4
    label.padding_right=4
    icon.padding_left=4
    icon.padding_right=4
)
sketchybar --default "${default[@]}"

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
# source $ITEM_DIR/spaces.sh
source $ITEM_DIR/window_title.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
