#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	menubar_opacity 1.0 \
	window_placement second_child \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:32:0 \
	focus_follows_mouse on \
	mouse_follows_focus on

# mouse_follows_focus on \
# focus_follows_mouse off \
# window_zoom_persist on \
# window_shadow on \
# window_animation_duration 0.0 \
#   window_animation_easing ease_out_circ \
#   window_opacity_duration 0.0 \
#   active_window_opacity 1.0 \
#   normal_window_opacity 0.90 \
# window_opacity off \
# insert_feedback_color 0xffd75f5f \
# window_origin_display default \
# display_arrangement_order default \
# split_ratio 0.50 \
#   split_type auto \
#   auto_balance off \
# external_bar                 off:40:0       \
# top_padding 12 \
#   bottom_padding 12 \
#   left_padding 12 \
#   right_padding 12 \
#   window_gap 06 \

echo "yabai configuration loaded.."
# yabai -m config layout bsp
#
# yabai -m config window_placement second_child
#
# yabai -m config mouse_follows_focus on
#
# yabai -m config mouse_modifier alt
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
#
# yabai -m mouse_drop_action swap
#
#
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^OpenGL Renderer$" manage=off
